<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Pulse.Core\Pulse.Core.csproj" />
    <ProjectReference Include="..\Pulse.Providers\Pulse.Providers.csproj" />
    <ProjectReference Include="..\Pulse.Storage\Pulse.Storage.csproj" />
    <ProjectReference Include="..\Pulse.Diagnostics\Pulse.Diagnostics.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

</Project>
